project:
  type: website
  output-dir: _site
website:
  title: "Machine Learnings"
  description: "notes from my explorations in machine learning"
  repo-url: https://github.com/chuckfinca/machine_learnings