project:
  type: website
  output-dir: _site
website:
  title: "Machine Learnings"
  description: "notes from my explorations in machine learning"
  repo-url: https://github.com/chuckfinca/machine_learnings

  navbar:
    background: dark
    logo: logo.png
    right:
      - text: About
        href: about.qmd
          
    tools:
      - icon: github
        href: https://github.com/chuckfinca
        text: Charles on Github
      - icon: twitter
        href: https://twitter.com/dynamics
        text: Charles on Twitter
      - icon: linkedin
        href: https://www.linkedin.com/in/charlesfeinn
        text: Charles on Linkedin